name: Feature CI Pipeline

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        uses: s4u/maven-install@v2
        with:
          maven-version: '4.0.0'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Merge to develop
        if: startsWith(github.ref, 'refs/heads/feature/') && success()
        run: |
          git fetch origin develop
          git checkout develop
          git merge feature/${{ github.head_ref }}
          git push origin develop
